/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase02;

import javax.swing.JOptionPane;
import proyectopilagenerica.Pila;

/**
 *
 * @author Sistemas
 */
public class FrmClase02 extends javax.swing.JFrame {

    /**
     * Creates new form FrmClase02
     */
    public FrmClase02() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public boolean verificaParentesis(String expresion){
        int n=expresion.length(),i;
        Pila<Character> pc = new Pila();
        char car;
        for(i=0;i<n;i++)
        {
            car=expresion.charAt(i);
            if(car=='(')
                pc.push(car);
            else
                if(car==')')
                {
                    if(pc.empty())
                        return false;
                    else
                        car=pc.pop();
                }
        }
        if(pc.empty())
            return true;
        else
            return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtExpresion = new javax.swing.JTextField();
        btnVeririfacr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExpresion.setBorder(javax.swing.BorderFactory.createTitledBorder("EXPRESION"));
        getContentPane().add(txtExpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, -1));

        btnVeririfacr.setText("VERIFICAR");
        btnVeririfacr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeririfacrActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeririfacr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVeririfacrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeririfacrActionPerformed
        // TODO add your handling code here:
        String expresion= txtExpresion.getText();
        if(verificaParentesis(expresion))
            JOptionPane.showMessageDialog(null,"Parrentesis correctos");
        else
            JOptionPane.showMessageDialog(null,"Parrentesis NO estan correctos");
    }//GEN-LAST:event_btnVeririfacrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClase02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClase02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClase02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClase02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClase02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVeririfacr;
    private javax.swing.JTextField txtExpresion;
    // End of variables declaration//GEN-END:variables
}
